Repository Hepheir/BOJ-Offline-Judge, pull requests merged in 2021-06, with the labels that each got.

#35 Wrap `Document` and `Rule` with `@dataclasses.dataclass`
  boj/python/core/problem.py
Labels: type: others

#36 `Crawler.get()` 메소드를 구현함
  boj/python/core/web.py
  boj/python/core/web_test.py
Labels: type: others

#38 `Document.title`에서 `Problem.title`로 변경
  boj/python/core/problem.py
Labels: type: others

#40 Fix `unittest` not discovering tests on VS Code
  .gitignore
  .pylintrc
  boj/python/__init__.py
  boj/python/core/__init__.py
  boj/python/core/web_test.py
  requirements.txt
Labels: type: bug

#42 Create unittest for `Problem.load()`
  .tmp/.gitkeep
  .tmp/1000/data/sample-1.in
  .tmp/1000/data/sample-1.out
  .tmp/1000/document/desc.html
  .tmp/1000/document/hint.html
  .tmp/1000/document/input.html
  .tmp/1000/document/output.html
  .tmp/1000/info.json
  .tmp/1000/rule.json
  boj/python/core/problem.py
  boj/python/core/problem_test.py
Labels: type: internal-todo

#44 README.md 에 현재 개발 상황과 관련없는 내용 삭제
  README.md
  Update.md
Labels: documentation
